name: Mobile Mercenary
favicon: null
layout_spectrum: 0.2931289514526725
typography_spectrum: 0.43998
title: Mobile developers for hire...anywhere.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2c2c'
    - '#004273'
    - '#007ac3'
    - '#000000'
    - '#000080'
  brandStrength: 0.24167914898134768
  lightness: 0.07338121137581766
  saturation: 0.9312970880419016
  rhythmicContrast: 0.4766477760858834
purpose: []
